language: node_js
sudo: true
node_js:
  - "8.11.2"
addons:
  apt:
    packages:
    - python-pip

git:
  submodules: false

before_install:
  - sudo pip install s3cmd
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --remote --recursive

script:
  - npm run-script test-travis
  - npm run deploy

deploy:
  provider: npm
  email: vyacheslav.chub@valor-software.com
  api_key:
    secure: $GITHUB_TOKEN
  on:
    branch: develop
    node: 8.11.2
    condition: "-e /tmp/deployment.flag"

branches:
  only:
  - master
  - develop
  - development
  - stage
