import {
  RESERVED_CONCEPT,
  RESERVED_CONCEPT_TYPE,
  RESERVED_DOMAIN,
  RESERVED_DRILL_UP
} from 'ddf-query-validator';
import { BASE_PATH, WS_TESTING_PATH } from '../../test/common';
import * as path from 'path';

const ALL_CONCEPTS: string[] = [ '', ' ', RESERVED_CONCEPT, RESERVED_CONCEPT_TYPE, RESERVED_DOMAIN, RESERVED_DRILL_UP, 'company', 'english_speaking', 'company_scale', 'name', 'anno', 'lines_of_code', 'region', 'country', 'latitude', 'longitude', 'full_name_changed', 'project', 'additional_column', 'meeting_style', 'popular_appeal', 'methodology' ];

export const description = 'Autogenerated tests for concepts';
export const initData = { };
export const testsDescriptors = {
  [description]: ALL_CONCEPTS.map((concept: string) => ({
    itTitle: `should be fine for concept '${concept}'`,
    query: {
      repositoryPath: path.join(BASE_PATH, WS_TESTING_PATH, 'master-HEAD'),
      dataset: WS_TESTING_PATH,
      from: 'concepts',
      select: {key: ['concept']},
      where: {
        concept
      }
    }
  }))
};
