export declare const description = "Autogenerated tests for concepts";
export declare const initData: {};
export declare const testsDescriptors: {
    [description]: {
        itTitle: string;
        query: {
            repositoryPath: string;
            dataset: string;
            from: string;
            select: {
                key: string[];
            };
            where: {
                concept: string;
            };
        };
    }[];
};
